@startuml
ingest_source -> receiving_entity: Authentication request
receiving_entity --> ingest_source: Authentication response

ingest_source -> receiving_entity: POST CMAF header
receiving_entity --> ingest_source: 200 OK

ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 200 OK 

ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 200 OK

ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 200 OK
ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 200 OK
ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 412 Precondition Failed error
ingest_source -> receiving_entity: POST CMAF header
receiving_entity --> ingest_source: 200 OK
ingest_source -> receiving_entity: POST CMAF segment
receiving_entity --> ingest_source: 200 OK
ingest_source -> receiving_entity: POST CMAF segment with the lmsg brand
receiving_entity --> ingest_source: 200 OK
@enduml
