@startuml
Ingest_Source -> Media_processing_entity: Authentication Request
Media_processing_entity --> Ingest_Source: Authentication Response

Ingest_Source -> Media_processing_entity: HTTP POST CMAF Header
Media_processing_entity --> Ingest_Source: 200 OK

Ingest_Source -> Media_processing_entity: HTTP POST CMAF Segment
Media_processing_entity --> Ingest_Source: 200 OK 

Ingest_Source -> Media_processing_entity: HTTP POST CMAF Segment
Media_processing_entity --> Ingest_Source: 200 OK

Ingest_Source -> Media_processing_entity: CMAF Segment
Media_processing_entity --> Ingest_Source: 200 OK
Ingest_Source -> Media_processing_entity: CMAF Segment
Media_processing_entity --> Ingest_Source: 200 OK
Ingest_Source -> Media_processing_entity: CMAF Segment
Media_processing_entity --> Ingest_Source: Error HTTP 412
Ingest_Source -> Media_processing_entity: CMAF Header
Media_processing_entity --> Ingest_Source: 200 OK
Ingest_Source -> Media_processing_entity: CMAF Segment
Media_processing_entity --> Ingest_Source: 200 OK
Ingest_Source -> Media_processing_entity: CMAF Segment with lmsg brand
Media_processing_entity --> Ingest_Source: 200 OK
@enduml
